blank_issues_enabled: false
contact_links:
  - name: NDK Suppor
    url: https://github.com/nguyenkhanh-k2
    about: Please ask and answer questions here.
  - name: Fca-Sumi-Remake Bug 
    url: https://github.com/nguyenkhanh-k2/Fca-Sumi-Remake/issues
    about: Please report security vulnerabilities here.
